#!/usr/bin/env python3
"""OutSpread stimulus generation scaffold for M1."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


STIMULI = [
    {"id": "impulse", "description": "Single-sample impulse for timing and IR-style checks."},
    {"id": "silence", "description": "Silence bed for noise-floor and stability checks."},
    {"id": "click_train", "description": "Sparse transient train for onset and predelay checks."},
    {"id": "sine_100hz", "description": "100 Hz sine for low-frequency behavior checks."},
    {"id": "sine_1khz", "description": "1 kHz sine for mid-band behavior checks."},
    {"id": "sine_10khz", "description": "10 kHz sine for high-frequency behavior checks."},
    {"id": "log_sweep", "description": "Logarithmic sweep for broad transfer probing."},
    {"id": "white_noise_burst", "description": "White-noise burst for broadband transient response."},
    {"id": "pink_noise_burst", "description": "Pink-noise burst for shaped broadband response."},
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create OutSpread stimulus scaffold metadata."
    )
    parser.add_argument(
        "--mode",
        default="scaffold",
        help="Execution mode. Only 'scaffold' is implemented in this ticket.",
    )
    parser.add_argument(
        "--outdir",
        default="tests/_generated/stimuli",
        help="Output directory for generated stimuli metadata or files.",
    )
    return parser.parse_args()


def ensure_supported_mode(mode: str) -> None:
    if mode == "scaffold":
        return
    raise SystemExit(
        f"error: mode '{mode}' is not implemented in this ticket. "
        "Use --mode scaffold to create stimulus metadata without audio files."
    )


def main() -> int:
    args = parse_args()
    ensure_supported_mode(args.mode)

    repo_root = Path(__file__).resolve().parent.parent
    outdir = (repo_root / args.outdir).resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    metadata_path = outdir / "stimuli_manifest.json"
    note_path = outdir / "SCAFFOLD_NOTE.txt"

    metadata = {
        "schemaVersion": 1,
        "generatedAt": datetime.now().isoformat(timespec="seconds"),
        "mode": args.mode,
        "scaffoldOnly": True,
        "audioGenerated": False,
        "outputDirectory": str(outdir.as_posix()),
        "stimuli": STIMULI,
        "notes": [
            "This ticket creates scaffold metadata only.",
            "No WAV files were generated by scripts/generate_stimuli.py in this ticket.",
            "Future tickets may replace this scaffold with real audio generation while preserving the stimulus IDs.",
        ],
    }

    with metadata_path.open("w", encoding="utf-8") as handle:
        json.dump(metadata, handle, indent=2)
        handle.write("\n")

    note_path.write_text(
        "OutSpread stimuli scaffold only.\n"
        "No audio files were generated by scripts/generate_stimuli.py in this ticket.\n",
        encoding="utf-8",
    )

    print(f"Created stimulus scaffold directory: {outdir}")
    print(f"Wrote metadata: {metadata_path}")
    print("No WAV files were generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
